### ISSUE TITLE
Start Date , End date for customer endpoint not working. 

### ISSUE THREAD

**Issue by jasminder** [Checkfront/PHP-SDK#13]
I want to grab last 100 customers . 
Example : 
```
$data = array("limit"=>100,"start_date"=>20200410,'end_date'=>20200415);
$item = $Checkfront->get('customer',$data);
```
It doesn't work hyphen date aswell. I am using php sdk

**Comment by brettgoss** [comment]
Hi @jasminder - the customer endpoint doesn't support a start date parameter, since a customer object isn't time based. For a list of supported parameters, I recommend referencing our api documentation found here: http://api.checkfront.com/ref/customer.html

**Comment by gegere** [comment]
@jasminder it is best to have a wrapper / sanity check to ensure the data is in the correct format. If you need help send me an email, I work with the Checkfront API almost daily.

**Comment by jasminder** [comment]
@brettgoss @gegere 
Can you please explain what process/code you would use to achieve what i want ?
I don’t want to hit api to get 3000 records every minute.

**Comment by brettgoss** [comment]
@jasminder I'm not too sure what your use case is, or what you're trying to achieve, but if you reach out to code@checkfront.com someone from our team should be able to get you pointed in the right direction!
