### ISSUE TITLE
Getting item info from booking/index API

### ISSUE THREAD

**Issue by bhashkar007** [Checkfront/PHP-SDK#14]
I am using [booking/index](https://api.checkfront.com/ref/booking/index.html#booking-index) which is returning booking detail. Is there any way, I can get item info or data for which booking was made.

**Comment by brettgoss** [comment]
Hi @bhashkar007,

The booked item information is not expanded at the top-level `booking/index` endpoint, however it is included in the `booking/{$bookingId}` endpoint. Once you have the bookingId that you are looking for (eg. ABCD-123456), you can make a subsequent request to `booking/ABCD-123456` to view the booked item details.

I hope this helps, but if you have any other questions, I would recommend reaching out to our support team at support@checkfront.com for further assistance.
